(test
 (name availability_test)
 (libraries alcotest plate_checker))

(test
 (name http_handler_test)
 (libraries alcotest plate_checker))

(test
 (name plate_validator_test)
 (libraries alcotest plate_checker))

(test
 (name dor_client_test)
 (libraries alcotest plate_checker))

(test
 (name html_form_test)
 (libraries alcotest plate_checker))

(test
 (name dor_bootstrap_test)
(libraries alcotest cohttp plate_checker))
